# Generated by Django 3.1.8 on 2021-07-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0003_auto_20210708_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='do_you_like_the_song',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
